@DividendsPageValidations
@Dividends3

Feature: Dividends Page Validations - Page Title Label Validations, Max Length, Invalid Char Validations

  @Dividendsinfo
  Scenario Outline: Dividends Form - Information Message Validations

    Given User login to STP site and open <FormType> form
    When  User reaches the field <FieldName> on <FormType> form
    And   User performs action to trigger information message for field "<FieldName>" on "<FormType>" form
    Then  information  message "<ErrorMessage>" is displayed successfully for field "<FieldName>" on "<FormType>" form
#    And   Footer Error message <ErrorMessage> shows up at the bottom for field <FieldName> on <FormType> form
#    And   Footer message Label <FooterLabel> shows up at the bottom for field <FieldName> on <FormType> form

    Examples:
      | FormType    | FieldName                                     | FooterLabel                                       | ErrorMessage               |
      | Dividends   | 3D1PaymentPeriodStartDateField                | 3D.1 Start date of payment period                 | The Start date of the payment period is usually less than the End Date of the payment period.                 |
      | Dividends   | 3D2PaymentPeriodEndDateField                  | 3D.2 End date of payment period                   | The End date of payment period is usually greater than the Start Date of the payment period.|
      | Dividends   | 4A4DRPPeriodOfCalculationStartDateField       | Start Date                                        | The Start date of the calculation period is usually less than the End Date.                            |
      | Dividends   | 4A7DRPSecuritiesIssueDateField                | 4A.7 DRP +securities +issue date                  | The date is in the past. Is this correct?                                                             |
      | Dividends   | 4B4BSBPeriodOfCalculationStartDatefield       | Start Date                                        | The Start date of the calculation period is usually less than the End Date.                                         |
      | Dividends   | 4B7BSPSecuritiesIssueDateField                | 4B.7 BSP +securities +issue date                  | The date is in the past. Is this correct?                                                              |
      | Dividends   | 4C5OtherPlanPeriodOfCalculationStartDateField | Start Date                                        | The Start date of the calculation period is usually less than the End Date.                                         |
      | Dividends   | 4C8OtherPlanSecuritiesIssueDateField          | 4C.8                                              | The date is in the past. Is this correct?                                                              |

#  Scenario Outline: Dividends - Warning Message Validations
#
#    Given User login to STP site and open <FormType> form
#    When  User reaches the field <FieldName> on <FormType> form
#    And   User performs action to trigger warning message for field <FieldName> on <FormType> form
#    Then  Warning message <ErrorMessage> is displayed successfully for field <FieldName> on <FormType> form
#    And   Footer Error message <ErrorMessage> shows up at the bottom for field <FieldName> on <FormType> form
#    And   Footer message Label <FooterLabel> shows up at the bottom for field <FieldName> on <FormType> form
#
#    Examples:
#      | FormType         | FieldName               | FooterLabel                                     | ErrorMessage               |
#      | Dividends  | 16ASXSecurityCodeField  | 1.6 ASX +Security Code for Interest Payment     | ASX has an existing corporate action record for this security. Please note that two or more corporate actions on the same security may not run with different record dates if the timetables result in overlapping (but not identical) ex-periods. It is permissible to run different corporate actions with the same record date except in the case of reorganisations - consolidations/splits which cannot run at the same time as any other corporate action for that entity. ASX suggests you contact your Listing Adviser prior to submission to check the validity of the corporate action you are proposing to announce. You may submit this announcement, however a warning will be presented to ASX Market Announcements Office for review prior to release to market.                   |

  @DividendsMax
  Scenario Outline: Dividends Form - Max Length, Invalid Char Validations, Negative Value

    Given User login to STP site and open <FormType> form
    When  User reaches the field <FieldName> on <FormType> form
    And   User fills desired field <FieldName> on <FormType> form with desired value <FieldValue>
    Then  <ErrorMessage> shows up successfully for field <FieldName> on <FormType> form
#    And   Footer Error message <ErrorMessage> shows up at the bottom for field <FieldName> on <FormType> form
#    And   Footer message Label <FooterLabel> shows up at the bottom for field <FieldName> on <FormType> form

    Examples:
      | FormType     | FieldName                                                  | FieldValue              | ErrorMessage                                                                                                           | FooterLabel                              |
      | Dividends    | 2A7aCommentField1                                          | InvalidCharText         | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 1000 characters may be entered.           | Comments                       |
      | Dividends    | 2A7aCommentField1                                          | 1000PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 1000 characters may be entered.          | Comments                   |
      | Dividends    | 2A9TotalDividendOrDistributionAmountPerSecurityField       | InvalidCharText         | Missing or incorrect value                                                                             |  2A.9 Total dividend/distribution payment amount per +security (in primary currency) for all dividends/distributions notified in this form:                        |
#      | Dividends    | 2A9TotalDividendOrDistributionAmountPerSecurityField       | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                      | 2A.9 Total dividend/distribution payment amount per +security (in primary currency) for all dividends/distributions notified in this form:                          |
      | Dividends    | 2B2CurrencyDescriptionArrangementField                     | InvalidCharText         | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered.                                       |  2B.2 Please provide a description of your currency arrangements                                                                                                                                                                   |
      | Dividends    | 2B2CurrencyDescriptionArrangementField                     | 2000PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered.                                                                                                                                                                       |                                                                                      |
      | Dividends    | 2B2aPaymentCurrencyEquivalentPerSecurityField1             | InvalidCharText         | Missing or incorrect value                                                                                                                                                                                               |Payment currency equivalent amount per security                                                                                                                                                                                 |
      | Dividends    | 2B2aPaymentCurrencyEquivalentPerSecurityField1             | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                                                            |Payment currency equivalent amount per security                                                                                                                                                                                 |
      | Dividends    | 2B2bCurrencyEquivalentMethodDescriptionField               | InvalidCharText         | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 254 characters may be entered.                                                                                              |2B.2b Please provide the exchange rates used for non-primary currency payments                                                                                                                                                  |
      | Dividends    | 2B2bCurrencyEquivalentMethodDescriptionField               | 254PlusCharText         | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 254 characters may be entered.                                                                                              |2B.2b Please provide the exchange rates used for non-primary currency payments                                                                                                                                                  |
      | Dividends    | 3A1aOrdinaryDividendDistributionEstimatedAmountPerSecurityField    | InvalidCharText             | Missing or incorrect value           | 3A.1a Ordinary dividend/distribution estimated amount per +security:                       |
      | Dividends    | 3A1aOrdinaryDividendDistributionEstimatedAmountPerSecurityField    | 5Before8AfterDecimal        | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.              | 3A.1a Ordinary dividend/distribution estimated amount per +security:       |
#      | Dividends    | 3A1aOrdinaryDividendDistributionEstimatedAmountPerSecurityField    |NegativeValue          | This value cannot be less than zero                       |                             |
      | Dividends    | 3A1bOrdinaryDividendDistributionAmountPerSecurityField     | InvalidCharText         | Missing or incorrect value                                                                          | 4.1b *Split ratio: the +securities will be split on the basis that every                   |
      | Dividends    | 3A1bOrdinaryDividendDistributionAmountPerSecurityField     | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                      | 4.1b *Split ratio: the +securities will be split on the basis that every                         |
#      | Dividends    | 3A1bOrdinaryDividendDistributionAmountPerSecurityField               |NegativeValue          | This value cannot be less than zero                       |                            |
      | Dividends    | 3A3PercentageOfFrankedOrdinaryDividendDistributionField    | InvalidCharText         | Missing or incorrect value           | 3A.3 Percentage of ordinary dividend/distribution that is franked:                    |
      | Dividends    | 3A3PercentageOfFrankedOrdinaryDividendDistributionField    | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.                | 3A.3 Percentage of ordinary dividend/distribution that is franked:                        |
      | Dividends    | 3A3aApplicableCorporateTaxRateForFrankingCreditField       | InvalidCharText         | Missing or incorrect value                                                  |3A.3a Applicable corporate tax rate for franking credit (%):                               |
#      | Dividends    | 3A3PercentageOfFrankedOrdinaryDividendDistributionField                                          |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3A3aApplicableCorporateTaxRateForFrankingCreditField       | 100PlusValue            | This field cannot be less than 0% and cannot be greater than 100%                                                  |3A.3a Applicable corporate tax rate for franking credit (%):                               |
      | Dividends    | 3A3aApplicableCorporateTaxRateForFrankingCreditField       | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point.This field cannot be less than 0% and cannot be greater than 100%| 3A.3a Applicable corporate tax rate for franking credit (%):                 |
#      | Dividends    | 3A3aApplicableCorporateTaxRateForFrankingCreditField                                             |NegativeValue          |  This value cannot be less than zero                      |                           |
      | Dividends    | 3A4OrdinaryDividendsDistributionFrankedAmountPerSecurityField       | InvalidCharText            | Missing or incorrect value                                                  |3A.4 Ordinary dividend/distribution franked amount per +security:                               |
      | Dividends    | 3A4OrdinaryDividendsDistributionFrankedAmountPerSecurityField       | 5Before8AfterDecimal       | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                  |3A.4 Ordinary dividend/distribution franked amount per +security:                              |
#      | Dividends    | 3A4OrdinaryDividendsDistributionFrankedAmountPerSecurityField    |NegativeValue          | This value cannot be less than zero                       |                             |
      | Dividends    | 3A5PercentageAmountOfUnfrankedDividendField                | InvalidCharText         | Missing or incorrect value                                                  |3A.5 Percentage amount of dividend which is unfranked:                             |
      | Dividends    | 3A5PercentageAmountOfUnfrankedDividendField                | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.                                | 3A.5 Percentage amount of dividend which is unfranked:                             |
#      | Dividends    | 3A5PercentageAmountOfUnfrankedDividendField |NegativeValue          | This value cannot be less than zero                       |                               |
      | Dividends    | 3A6OrdinaryDividendUnfrankedAmountPerSecurityField         | InvalidCharText         | Missing or incorrect value  | 3A.6 Ordinary dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                   |
      | Dividends    | 3A6OrdinaryDividendUnfrankedAmountPerSecurityField         | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3A.6 Ordinary dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                        |
      | Dividends    | 3A7OrdinaryDividendDistributionConduitForeignIncomeAmountField       | InvalidCharText           |Missing or incorrect value | 3A.7 Ordinary dividend/distribution conduit foreign income amount per security:                   |
      | Dividends    | 3A7OrdinaryDividendDistributionConduitForeignIncomeAmountField       | 5Before8AfterDecimal      | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3A.7 Ordinary dividend/distribution conduit foreign income amount per security:                       |
      | Dividends    | 3B1aSpecialDividendDistributionEstimatedAmountField        | InvalidCharText         | Missing or incorrect value           | 3B.1a Special dividend/distribution estimated amount per +security                       |
      | Dividends    | 3B1aSpecialDividendDistributionEstimatedAmountField        | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.              | 3B.1a Special dividend/distribution estimated amount per +security:       |
#      | Dividends    | 3B1aSpecialDividendDistributionEstimatedAmountField                                              |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B1bSpecialDividendDistributionAmountPerSecurityField      | InvalidCharText         | Missing or incorrect value                                                                          | 3B.1b Special dividend/distribution amount per +security                   |
      | Dividends    | 3B1bSpecialDividendDistributionAmountPerSecurityField      | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                      | 3B.1b Special dividend/distribution amount per +security                         |
#      | Dividends    | 3B1bSpecialDividendDistributionAmountPerSecurityField                                            |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B3PercentageOfFrankedSpecialDividendDistributionField     | InvalidCharText         | Missing or incorrect value           | 3B.3 Percentage of special dividend/distribution that is franked:                    |
      | Dividends    | 3B3PercentageOfFrankedSpecialDividendDistributionField     | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.                | 3B.3 Percentage of special dividend/distribution that is franked:                        |
#      | Dividends    | 3B3PercentageOfFrankedSpecialDividendDistributionField                                           |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B3aApplicableCorporateTaxRateForFrankingCreditField       | InvalidCharText         | Missing or incorrect value                                                  |3B.3a Applicable corporate tax rate for franking credit (%)                              |
      | Dividends    | 3B3aApplicableCorporateTaxRateForFrankingCreditField       | 100PlusValue            | This field cannot be less than 0% and cannot be greater than 100%                                                  |3B.3a Applicable corporate tax rate for franking credit (%):                               |
      | Dividends    | 3B3aApplicableCorporateTaxRateForFrankingCreditField       | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point.This field cannot be less than 0% and cannot be greater than 100%| 3B.3a Applicable corporate tax rate for franking credit (%):                 |
#      | Dividends    | 3B3aApplicableCorporateTaxRateForFrankingCreditField                                             |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B4SpecialFrankedAmountPerSecurityField                    | InvalidCharText         | Missing or incorrect value                                                  |3B.4 Special dividend/distribution franked amount per +security:                               |
      | Dividends    | 3B4SpecialFrankedAmountPerSecurityField                    | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                  |3B.4 Special dividend/distribution franked amount per +security:                              |
#      | Dividends    | 3B4SpecialFrankedAmountPerSecurityField                                                          |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B5PercentageAmountOfUnfrankedSpecialDividendField         | InvalidCharText         | Missing or incorrect value                                                  |3B.5 Percentage of special dividend/distribution that is unfranked:                             |
      | Dividends    | 3B5PercentageAmountOfUnfrankedSpecialDividendField         | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.                                | 3B.5 Percentage of special dividend/distribution that is unfranked:                             |
#      | Dividends    | 3B5PercentageAmountOfUnfrankedSpecialDividendField                                               |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B6SpecialDividendUnfrankedAmountPerSecurityField          | InvalidCharText         | Missing or incorrect value  | 3B.6 Special dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                   |
      | Dividends    | 3B6SpecialDividendUnfrankedAmountPerSecurityField          | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3B.6 Special dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                        |
#      | Dividends    | 3B6SpecialDividendUnfrankedAmountPerSecurityField                                                |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3B7ForeignIncomeAmountPerSecurityField                     | InvalidCharText         | Missing or incorrect value  | 3B.7 Special dividend/distribution conduit foreign income amount per +security:                   |
      | Dividends    | 3B7ForeignIncomeAmountPerSecurityField                     | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3B.7 Special dividend/distribution conduit foreign income amount per +security:                       |
#      | Dividends    | 3B7ForeignIncomeAmountPerSecurityField                                                           |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C1aScripDividendDistributionEstimatedAmountPerSecurityField         | InvalidCharText           | Missing or incorrect value           | 3B.1a Special dividend/distribution estimated amount per +security                       |
      | Dividends    | 3C1aScripDividendDistributionEstimatedAmountPerSecurityField         | 5Before8AfterDecimal      | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.              | 3B.1a Special dividend/distribution estimated amount per +security:       |
#      | Dividends    | 3C1aScripDividendDistributionEstimatedAmountPerSecurityField                                     |NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C1bScripDividendDistributionAmountPerSecurityField        | InvalidCharText         | Missing or incorrect value                                                                          | 3B.1b Special dividend/distribution amount per +security                   |
      | Dividends    | 3C1bScripDividendDistributionAmountPerSecurityField        | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                                      | 3B.1b Special dividend/distribution amount per +security                         |
#      | Dividends    | 3C1bScripDividendDistributionAmountPerSecurityField        | NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C2ScripRatioMultiplier                                    | InvalidCharText         | Missing or incorrect value           | 3C.2 Scrip ratio: the scrip dividend/distribution will be on the basis that:                    |
      | Dividends    | 3C2ScripRatioMultiplier                                    | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 4 digits after the decimal point. The value must be greater than zero.                | 3C.2 Scrip ratio: the scrip dividend/distribution will be on the basis that:                        |
      | Dividends    | 3C2ScripRatioDiviserField                                  | InvalidCharText         | Missing or incorrect value              | +security (/ies) will be paid for every                        |
      | Dividends    | 3C2ScripRatioDiviserField                                  | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 4 digits after the decimal point. The value must be greater than zero.                | +security (/ies) will be paid for every:                        |
      | Dividends    | 3C2ScripRatioMultiplier                                    | NegativeValue           | This field allows up to 5 digits before the decimal point and 4 digits after the decimal point. The value must be greater than zero.                      |                              |
      | Dividends    | 3C2ScripRatioDiviserField                                  | NegativeValue           | This field allows up to 5 digits before the decimal point and 4 digits after the decimal point. The value must be greater than zero.                     |                              |
      | Dividends    | 3C7PercentageOfFrankedScripDividendDistributionField       | InvalidCharText         | Missing or incorrect value                                                  |3C.7 percentage of scrip dividend/distribution that is franked:                             |
      | Dividends    | 3C7PercentageOfFrankedScripDividendDistributionField       | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.                                                  |3C.7 percentage of scrip dividend/distribution that is franked:                               |
#      | Dividends    | 3C7PercentageOfFrankedScripDividendDistributionField       | NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C7aApplicableCorporateTaxRateForFrankingCreditField       | InvalidCharText         | Missing or incorrect value| 3C.7a Applicable corporate tax rate for franking credit (%):                 |
      | Dividends    | 3C7aApplicableCorporateTaxRateForFrankingCreditField       | 100PlusValue            | This field cannot be less 0% and cannot be greater than 100%                                                |3C.7a Applicable corporate tax rate for franking credit (%):                                |
      | Dividends    | 3C7aApplicableCorporateTaxRateForFrankingCreditField       | 3Before4After           | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point.This field cannot be less 0% and cannot be greater than 100%                                                  |3C.7a Applicable corporate tax rate for franking credit (%):                               |
#      | Dividends    | 3C7aApplicableCorporateTaxRateForFrankingCreditField       | NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C8ScripDividendsDistributionFrankedAmountField            | InvalidCharText         | Missing or incorrect value                                                  |3C.8 Scrip dividend/distribution franked amount per +security:                             |
      | Dividends    | 3C8ScripDividendsDistributionFrankedAmountField            | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.                                | 3C.8 Scrip dividend/distribution franked amount per +security:                             |
#      | Dividends    | 3C8ScripDividendsDistributionFrankedAmountField            | NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C9PercentageAmountOfUnfrankedScripField                   | InvalidCharText         | Missing or incorrect value  | 3C.9 Percentage of scrip dividend/distribution that is unfranked:                   |
      | Dividends    | 3C9PercentageAmountOfUnfrankedScripField                   | 5Before8AfterDecimal    | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.  | 3C.9 Percentage of scrip dividend/distribution that is unfranked:                        |
#      | Dividends    | 3C9PercentageAmountOfUnfrankedScripField                   | NegativeValue          | This value cannot be less than zero                       |                              |
      | Dividends    | 3C10ScripDividendUnfrankedAmountField                      | InvalidCharText         | Missing or incorrect value  | 3C.10 Scrip dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                   |
      | Dividends    | 3C10ScripDividendUnfrankedAmountField                      | 5Before8AfterDecimal    | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3C.10 Scrip dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                       |
#      | Dividends    | 3C10ScripDividendUnfrankedAmountField                      | NegativeValue          |  This value cannot be less than zero                      |                             |
      | Dividends    | 3C11ScripDividendDistributionConduitForeignIncomeAmountField         | InvalidCharText           | Missing or incorrect value  | 3C.11 Scrip dividend/distribution conduit foreign income amount per +security:                   |
      | Dividends    | 3C11ScripDividendDistributionConduitForeignIncomeAmountField         | 5Before8AfterDecimal      | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value can be zero or greater.  | 3C.11 Scrip dividend/distribution conduit foreign income amount per +security:                       |
      | Dividends    | 3D6DividendDistributionBaseRateField                        | InvalidCharText        | Missing or incorrect value  | 3D.6 Dividend/distribution base rate (pa)Missing or incorrect value entered.                       |
      | Dividends    | 3D6DividendDistributionBaseRateField                        | 3Before4After          | Missing or incorrect value entered. This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.  | 3D.6 Dividend/distribution base rate (pa)Missing or incorrect value entered.                        |
      | Dividends    | 3D7DividendDistributionBaseRateDescriptionField             | InvalidCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered.  | 3D.7 Comments on how dividend/distribution base rate is set                   |
      | Dividends    | 3D7DividendDistributionBaseRateDescriptionField             | 500PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered.  | 3D.7 Comments on how dividend/distribution base rate is set                      |
      | Dividends    | 3D8DividendDistributionMarginField                          | InvalidCharText        | Missing or incorrect value  | 3D.8 Dividend/distribution margin:                       |
      | Dividends    | 3D8DividendDistributionMarginField                          | 3Before4After          | Missing or incorrect value entered. This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.  | 3D.8 Dividend/distribution margin:                        |
      | Dividends    | 3D9DividendDistributionMarginDescriptionField               | InvalidCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered. | 3D.9 Comments on how dividend/distribution margin is set:                       |
      | Dividends    | 3D9DividendDistributionMarginDescriptionField               | 500PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered.  | 3D.9 Comments on how dividend/distribution margin is set:                        |
      | Dividends    | 3D10DividendDistributionOtherRateField                      | InvalidCharText        | Missing or incorrect value  | 3D.10 Any other rate / multiplier used in calculating dividend/distribution rate:                      |
      | Dividends    | 3D10DividendDistributionOtherRateField                      | 3Before4After          | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be positive or negative. | 3D.10 Any other rate / multiplier used in calculating dividend/distribution rate:                        |
      | Dividends    | 3D11DividendDistributionOtherRateDescriptionField           | InvalidCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered.  | 3C.10 Scrip dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                       |
      | Dividends    | 3D11DividendDistributionOtherRateDescriptionField           | 500PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered.  | 3C.10 Scrip dividend/distribution unfranked amount per +security excluding conduit foreign income amount:                        |
      | Dividends    | 3D13DividendDistributionRateCommentField                    | InvalidCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered.  | 3D.13 Comment on how total distribution rate is set:                      |
      | Dividends    | 3D13DividendDistributionRateCommentField                    | 2000PlusCharText       | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered.  | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 3E1TaxComponentsComments                                    | InvalidCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered. | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 3E1TaxComponentsComments                                    | 500PlusCharText        | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered. | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 3F2aNZDSupplementaryEstimatedAmountPerSecurity              | InvalidCharText        | Missing or incorrect value| 4A.3 DRP discount rate:                 |
      | Dividends    | 3F2aNZDSupplementaryEstimatedAmountPerSecurity              | 5Before8AfterDecimal   | This field allows up to 5 digits before the decimal point and 8 digits after the decimal point. The value must be greater than zero.                            |4A.3 DRP discount rate:                              |
      | Dividends    | 4A3DRPDiscountRateField                                     | InvalidCharText        | Missing or incorrect value| 4A.3 DRP discount rate:                 |
      | Dividends    | 4A3DRPDiscountRateField                                     | 100PlusValue           | This field cannot be less than 0% and cannot be greater than 100%                                                 |4A.3 DRP discount rate:                        |
      | Dividends    | 4A3DRPDiscountRateField                                     | 3Before4After          | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater.This field cannot be less than 0% and cannot be greater than 100%                            |4A.3 DRP discount rate:                              |
      | Dividends    | 4A3DRPDiscountRateField                                     | NegativeValue          | This field cannot be less than 0% and cannot be greater than 100%     |                             |
      | Dividends    | 4A5DRPPriceCalculationMethodologyField                 | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 4A5DRPPriceCalculationMethodologyField                 | 350PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 4A6DRPPriceField                                       | InvalidCharText             | Missing or incorrect value  | 4A.6 DRP Price (including any discount):                      |
      | Dividends    | 4A6DRPPriceField                                       | 9Before5After               | This field allows up to 9 digits before the decimal point and 5 digits after the decimal point. The value can be zero or greater. | 4A.6 DRP Price (including any discount):                        |
      | Dividends    | 4A9aDRPMinimumNumberOfSecuritiesRequiredField          | InvalidCharText             | Missing or incorrect integer value. | 4A.9a Minimum number of +securities required for DRP participation:                     |
      | Dividends    | 4A9bDRPMinimumField                                    | 14PlusDigits                | Please provide a minimum amount. Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4A.10b Maximum amount for DRP participation:                       |
      | Dividends    | 4A10aDRPMaximumNumberOfSecuritiesRequiredField         | InvalidCharText             | Missing or incorrect integer value. | 4A.10a Maximum number of +securities required for DRP participation:                     |
      | Dividends    | 4A10bDRPMaximumAmountField                             | 14PlusDigits                | Please provide a maximum amount. Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4A.10b Maximum amount for DRP participation:                       |
      | Dividends    | 4A10dDRPLimitsAtBeneficialLevelDescriptionField        | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 256 characters may be entered.| 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 4A10dDRPLimitsAtBeneficialLevelDescriptionField        | 256PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 256 characters may be entered. | 3D.13 Comment on how total distribution rate is set:                       |
      | Dividends    | 4A11aDRPParticipationConditionsDescriptionField        | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4A.11a Conditions for DRP participation:                     |
      | Dividends    | 4A11aDRPParticipationConditionsDescriptionField        | 350PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4A.11a Conditions for DRP participation:                       |
      | Dividends    | 4A12DRPPlanRulesURLField                               | InvalidCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4A.12 Link to a copy of the DRP plan rules:                       |
      | Dividends    | 4A12DRPPlanRulesURLField                               | 500PlusCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4A.12 Link to a copy of the DRP plan rules:                       |
      | Dividends    | 4A13DRPFurtherInfoField                                | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4A.13 Further information about the DRP:                      |
      | Dividends    | 4A13DRPFurtherInfoField                                | 2000PlusCharText            | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4A.13 Further information about the DRP:                      |
      | Dividends    | 4B3BSPDiscountRateField                                | InvalidCharText             | Missing or incorrect value| 4A.3 DRP discount rate:                 |
      | Dividends    | 4B3BSPDiscountRateField                                | 100PlusValue                | This field cannot be less than 0% and cannot be greater than 100%   |4B.3 BSP discount rate:                       |
      | Dividends    | 4B3BSPDiscountRateField                                | 3Before4After               | This field allows up to 3 digits before the decimal point and 4 digits after the decimal point.This field cannot be less than 0% and cannot be greater than 100%                            |4B.3 BSP discount rate:                             |
      | Dividends    | 4B3BSPDiscountRateField                                | NegativeValue               | This field cannot be less than 0% and cannot be greater than 100%     |                             |
      | Dividends    | 4B5BSPPriceCalculationMethodologyField                 | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4B.5 BSP price calculation methodology:                       |
      | Dividends    | 4B5BSPPriceCalculationMethodologyField                 | 350PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4B.5 BSP price calculation methodology:                       |
      | Dividends    | 4B6BSPPriceField                                       | InvalidCharText             | Missing or incorrect value  | 4B.6 BSP Price (including any discount):                      |
      | Dividends    | 4B6BSPPriceField                                       | 9Before4After               | This field allows up to 9 digits before the decimal point and 4 digits after the decimal point. The value can be zero or greater. | 4B.6 BSP Price (including any discount):                        |
      | Dividends    | 4B9aBSPMinimumNumberOfSecuritiesRequiredField          | InvalidCharText             | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4B.9a Minimum number of +securities required for BSP participation:                     |
      | Dividends    | 4B9bBSPMinimumAmountField                              | 14PlusDigits                | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4B.9b Minimum amount for BSP participation:                       |
#      | Dividends    | 4B10aBSPMaximumNumberOfSecuritiesRequired              | 14PlusDigits                | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places.||
      | Dividends    | 4B10aBSPMaximumNumberOfSecuritiesRequired              | InvalidCharText             | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. |4B.10a Maximum number of +securities required for BSP participation:                     |
      | Dividends    | 4B10bBSPMaximumAmountField                             | 14PlusDigits                | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4B.10b Maximum amount for BSP participation:                       |
      | Dividends    | 4B10bBSPMaximumAmountField                             | InvalidCharText             | Please provide a minimum or maximum amount (whichever is relevant). Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. |4B.10b Maximum amount for BSP participation:                       |
      | Dividends    | 4B10dBSPLimitsAtBeneficialLevelDescriptionField        | 256PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 256 characters may be entered.| 4B.10d Instructions regarding application of limits at beneficial level:                       |
      | Dividends    | 4B11aBSPParticipationConditionsDescriptionField        | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4B.11a Conditions for BSP participation:                     |
      | Dividends    | 4B11aBSPParticipationConditionsDescriptionField        | 500PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4B.11a Conditions for BSP participation:                       |
      | Dividends    | 4B12BSPPlanRulesURLField                               | InvalidCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4B.12 Link to a copy of the BSP plan rules:                       |
      | Dividends    | 4B12BSPPlanRulesURLField                               | 500PlusCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4B.12 Link to a copy of the BSP plan rules:                     |
      | Dividends    | 4B13BSPFurtherInfoField                                | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4B.13 Further information about the BSP                      |
      | Dividends    | 4B13BSPFurtherInfoField                                | 2000PlusCharText            | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4B.13 Further information about the BSP                     |
      | Dividends    | 4C1OtherPlanNameField                                  | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 254 characters may be entered. | 4C.1 Name of the Plan:                      |
      | Dividends    | 4C1OtherPlanNameField                                  | 254PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 254 characters may be entered. | 4C.1 Name of the Plan:                        |
      | Dividends    | 4C4OtherPlanDiscountRateField                          | InvalidCharText             | Missing or incorrect value| 4C.4 Plan Discount Rate:                 |
      | Dividends    | 4C4OtherPlanDiscountRateField                          | 100PlusValue                | This field cannot be less 0% and cannot be greater than 100%     |4C.4 Plan Discount Rate:                        |
      | Dividends    | 4C4OtherPlanDiscountRateField                          | 500PlusCharText             | Missing or incorrect value                           |4C.4 Plan Discount Rate:                              |
      | Dividends    | 4C4OtherPlanDiscountRateField                          | NegativeValue               | This field cannot be less 0% and cannot be greater than 100%     |                             |
      | Dividends    | 4C6OtherPlanPriceCalculationMethodologyField           | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered.  | 4C.4 Plan Discount Rate:                    |
      | Dividends    | 4C6OtherPlanPriceCalculationMethodologyField           | 350PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' +. A maximum of 350 characters may be entered. | 4C.4 Plan Discount Rate:                       |
      | Dividends    | 4C10aOtherPlanMinimumNumberOfSecuritiesRequiredField   | InvalidCharText             | Missing or incorrect value | 4C.4 Plan Discount Rate:                     |
      | Dividends    | 4C10aOtherPlanMinimumNumberOfSecuritiesRequiredField   | 12PlusDigits                | This field allows a maximum of 12 digits. The value must be less than or equal to Maximum number of security. | 4C.4 Plan Discount Rate:                       |
      | Dividends    | 4C10bOtherPlanMinimumAmountField                       | InvalidCharText             | Please provide a minimum amount. Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4C.10a Minimum number of securities required for Plan participation:                     |
      | Dividends    | 4C10bOtherPlanMinimumAmountField                       | 14PlusDigits                | Please provide a minimum amount. Limit of 14 digits which may not be zero or less than zero and may not contain decimal places. | 4C.10b Minimum amount for Plan participation:                       |
      | Dividends    | 4C11aOtherPlanMaximumNumberOfSecuritiesRequiredField   | InvalidCharText             | Missing or incorrect value | 4C.10b Minimum amount for Plan participation:                    |
      | Dividends    | 4C11aOtherPlanMaximumNumberOfSecuritiesRequiredField   | 12PlusDigits                | This field allows a maximum of 12 digits. The value must be greater than or equal to Minimum number of security. | 4C.11a Maximum number of securities required for Plan participation:                       |
      | Dividends    | 4C13OtherPlanPlanRulesURLField                         | InvalidCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4C.13 Link to a copy of the Plan plan rules:                       |
      | Dividends    | 4C13OtherPlanPlanRulesURLField                         | 254PlusCharText             | The text you have entered may contain an invalid url format or you may have exceeded the maximum number of characters (maximum 254 characters) that may be entered. | 4C.13 Link to a copy of the Plan plan rules:                      |
      | Dividends    | 4C14OtherPlanFurtherInfoField                          | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4C.14 Further information about the Plan:                     |
      | Dividends    | 4C14OtherPlanFurtherInfoField                          | 2000PlusCharText            | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 2000 characters may be entered. | 4C.14 Further information about the Plan:                       |
      | Dividends    | 51FurtherInformationCommentField                       | InvalidCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered. | 5.1 Please provide any further information applicable to this dividend/distribution:                       |
      | Dividends    | 51FurtherInformationCommentField                       | 500PlusCharText             | Allowed characters include a-z A-Z 0-9 / - ? : ( ) . , ' += ! " % & * < > ; @ # _ . A maximum of 500 characters may be entered. | 5.1 Please provide any further information applicable to this dividend/distribution:                       |




  @DividendsPageTitle
  Scenario Outline: Dividends -  Page Title Label Validations

    Given User login to STP site and open <FormType> form
    When  User reaches the field <FieldName> on <FormType> form
    Then  Field <FieldName> on <FormType> form shows correct page title label <LabelText>

    Examples:
      | FormType     | FieldName                        | LabelText |
      | Dividends    | Part1PageTitleField              | Part 1 - Entity and announcement details                               |
      | Dividends    | Part2APageTitleField             | Part 2A - All dividends/distributions basic details           |
      | Dividends    | Part2BPageTitleField             | Part 2B - Currency Information  |
      | Dividends    | Part3APageTitleField             | Part 3A - Ordinary dividend/distribution   |
      | Dividends    | Part3BPageTitleField             | Part 3B - Special dividend/distribution   |
      | Dividends    | Part3CPageTitleField             | Part 3C - Scrip dividend/distribution  |
      | Dividends    | Part3DPageTitleField             | Part 3D - Preference +security distribution rate details    |
      | Dividends    | Part3EPageTitleField             | Part 3E - Other - distribution components / tax   |
      | Dividends    | Part3FPageTitleField             | Part 3F - NZD declared dividends/distributions - supplementary dividend/distribution   |
      | Dividends    | Part4APageTitleField             | Part 4A - +Dividend reinvestment plan (DRP)    |
      | Dividends    | Part4BPageTitleField             | Part 4B - Bonus +security plan or equivalent (BSP)   |
      | Dividends    | Part4CPageTitleField             | Part 4C - Other plan (Plan)  |
      | Dividends    | Part5PageTitleField              | Part 5 - Further information   |
