package Framework.Util;

public enum TestDataObject {
    TESTFILE,
    WEBSERVICE_ASX_EVT_OIIPINSTRUMENT,
    DATABASE_GOLDENSOURCE_NCORE,
    ESB_NCORE,
    DATABASE_TIBCO,
    WEBSERVICE_TIBCO,
    FTP_CHESSADAPTOR,
    FTP_MORNINGSTAR,
    DATABASE_ADW_LANDING;
}
